### ISSUE TITLE
ノーメソッドエラー

### ISSUE THREAD

**Issue by KenjiWatarai** [KenjiWatarai/exercises#1]
exercises/sample1.rb:35:in `proc': undefined method `+' for nil:NilClass (NoMethodError)
	from exercises/sample1.rb:46:in `<main>'

**Comment by KenjiWatarai** [comment]
正しい出力は「bsd=>mit」であるが、実際はエラーとなっている。
この出力をしている箇所は「p path[0] + " => " + @data[path[0]].to_s」である。
